
version: '3.3'

services:
  # PHP Application Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fund_transfer_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password@db:3306/fund_transfer_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - fund_transfer_network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: fund_transfer_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fund_transfer_network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: fund_transfer_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fund_transfer_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fund_transfer_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: fund_transfer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fund_transfer_network

volumes:
  mysql_data:
  redis_data:

networks:
  fund_transfer_network:
    driver: bridge
